version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  php1:
    build: ./php
    container_name: php_server_1
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      - db

  php2:
    build: ./php
    container_name: php_server_2
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      - db

  nginx1:
    image: nginx:latest
    container_name: nginx_server_1
    ports:
      - "8081:80"
    volumes:
      - ./laravel-app:/var/www/html
      - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1

  nginx2:
    image: nginx:latest
    container_name: nginx_server_2
    ports:
      - "8082:80"
    volumes:
      - ./laravel-app:/var/www/html
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2

volumes:
  db_data:
